---
title: "Vectors"
author: "Javier Patron"
date: "2022-08-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(palmerpenguins)
```

## Making some Vectors

```{r}
marmots <- c("blue", "green", 4, "yellow")

# Check for class

class(marmots)
```

# Make another animal

```{r}
pika <- c(12.4, 6.8, 2.9, 8.8, 8.5)
class(pika)

##--## Scalar Multiplier
scale_for_pika <- 5.2 * pika
scale_for_pika

```

### More Examples
```{r}
bananas <- c(1,2,3)
apples <- c(6,7,8)

#Multiplication
bananas*apples
#Sum
bananas + apples
#Resting
bananas - apples
#Dot Product
bananas %*% apples
```


### Sequences
Term is seq()
## Sintax
seq(a,b,c)
a= from
b= to
c= several stuff like (length=#, by=#)

```{r}
seq
```

### Matrices
# Term is matrix

##Sintax
# matrix(a,b,c,d)
# a -> data = (What do you wanna put in the matrix)
# b -> nrow = # (number of rows)
# c -> ncol = # (number of columns)
# d -> byrow = Boolean (If you want to put the data by columns (FALSE), or by rows (TRUE))


```{r}
my_values <- seq(1,10)
my_values

my_matrix <- matrix(data = my_values, nrow=2, ncol = 5, byrow=FALSE)
my_matrix

```


```{r}
glimpse(penguins)
```

